sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "pypy"
install: pip install tox
script: tox
after_success:
  - coveralls debug
branches:
  only:
    - develop
matrix:
  fast_finish: true